name: Test & Deploy | master

on:
  push:
    branches:
      - "master"
jobs:
  check_deploy_macos:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: './gradlew --no-daemon publishRelease -PpearxRepoUsername=${{ secrets.S_PEARX_REPO_USERNAME }} -PpearxRepoPassword=${{ secrets.S_PEARX_REPO_PASSWORD }} -Psigning.keyId=${{ secrets.S_PGP_KEY_PUBID }} -Psigning.password="${{ secrets.S_PGP_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=private.key -PgithubAccessToken="${{ secrets.S_GITHUB_RELEASE_TOKEN }}" -PsonatypeOssUsername="${{ secrets.S_SONATYPE_OSS_USERNAME }}" -PsonatypeOssPassword="${{ secrets.S_SONATYPE_OSS_PASSWORD }}" -Pmultigradle.publishHostExclusivesOnly=true'
  check_deploy_windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: 'CALL gradlew.bat --no-daemon publishRelease -PpearxRepoUsername=${{ secrets.S_PEARX_REPO_USERNAME }} -PpearxRepoPassword=${{ secrets.S_PEARX_REPO_PASSWORD }} -Psigning.keyId=${{ secrets.S_PGP_KEY_PUBID }} -Psigning.password="${{ secrets.S_PGP_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=private.key -PgithubAccessToken="${{ secrets.S_GITHUB_RELEASE_TOKEN }}" -PsonatypeOssUsername="${{ secrets.S_SONATYPE_OSS_USERNAME }}" -PsonatypeOssPassword="${{ secrets.S_SONATYPE_OSS_PASSWORD }}" -Pmultigradle.publishHostExclusivesOnly=true'
        shell: cmd
  check_deploy_linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: './gradlew --no-daemon release -PpearxRepoUsername=${{ secrets.S_PEARX_REPO_USERNAME }} -PpearxRepoPassword=${{ secrets.S_PEARX_REPO_PASSWORD }} -Psigning.keyId=${{ secrets.S_PGP_KEY_PUBID }} -Psigning.password="${{ secrets.S_PGP_KEY_PASSWORD }}" -Psigning.secretKeyRingFile=private.key -PgithubAccessToken="${{ secrets.S_GITHUB_RELEASE_TOKEN }}" -PsonatypeOssUsername="${{ secrets.S_SONATYPE_OSS_USERNAME }}" -PsonatypeOssPassword="${{ secrets.S_SONATYPE_OSS_PASSWORD }}"'